PREFIX fam: <http://www.ifi.uio.no/IN3060/family#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sim: <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

 CONSTRUCT {
  sim:Homer a foaf:Person .
  sim:Homer foaf:knows ?other .
  sim:Homer foaf:knows ?other2 .
 }
 WHERE {
  ?other a foaf:Person .
  ?other2 a foaf:Person ,
  ?other fam:isRelativeOf sim:Homer .
  sim:Homer fam:isRelativeOf ?other2 .
}
