CC=gcc
CFLAGS=-std=c99
default: all

all: task1 task2 task3 task4
task1: task1.c
	$(CC) $(CFLAGS) task1.c -o task1 -lm

task2: task2.c
	$(CC) $(CFLAGS) task2.c -o task2 -lm

task3: task3.c
	$(CC) $(CFLAGS) task3.c -o task3 -lm

task4: task4.c
	$(CC) $(CFLAGS) task4.c -o task4 -lm
